apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rust-processor-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dainmusty/aws-eks-multi-language-cicd-enterprise.git
    targetRevision: develop
    path: helm/per-service-charts/rust-service
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: polyglot-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
