############################################################
# KUBERNETES SERVICE ACCOUNT
#
# PURPOSE:
# Provides workload identity for the
# JavaScript API application.
#
# ENTERPRISE FEATURES:
# - IAM Roles for Service Accounts (IRSA)
# - Least privilege security
# - AWS workload identity
# - Kubernetes RBAC integration
############################################################

{{- if .Values.serviceAccount.create }}

apiVersion: v1

kind: ServiceAccount

metadata:

  name: {{ include "java-service.serviceAccountName" . }}

  labels:
    {{- include "java-service.labels" . | nindent 4 }}

  ##########################################################
  # AWS IAM ROLE ANNOTATION (IRSA)
  ##########################################################

  annotations:

    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

automountServiceAccountToken: true

{{- end }}