apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: java-service-dev:apps/Deployment:polyglot-dev/java-service-dev
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"java-service-dev:apps/Deployment:polyglot-dev/java-service-dev"},"labels":{"app.kubernetes.io/instance":"java-service-dev","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"java-service","app.kubernetes.io/version":"1.0.0","helm.sh/chart":"java-service-1.0.0"},"name":"java-service-dev","namespace":"polyglot-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"java-service-dev","app.kubernetes.io/name":"java-service"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":null,"labels":{"app":"java-service","app.kubernetes.io/instance":"java-service-dev","app.kubernetes.io/name":"java-service"}},"spec":{"containers":[{"env":[{"name":"SERVER_PORT","value":"8080"},{"name":"SPRING_PROFILES_ACTIVE","value":"production"}],"envFrom":[{"configMapRef":{"name":"java-service-dev"}},{"secretRef":{"name":"java-service-dev"}}],"failureThreshold":3,"image":"dainmusty/java-service:dev-latest","imagePullPolicy":"IfNotPresent","initialDelaySeconds":15,"livenessProbe":{"httpGet":{"path":"/actuator/health","port":8080}},"name":"java-service","periodSeconds":5,"ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/actuator/health","port":8080}},"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsNonRoot":true,"runAsUser":1000},"timeoutSeconds":3}],"securityContext":{"fsGroup":1000},"serviceAccountName":"java-service-dev"}}}}
  creationTimestamp: "2026-06-04T22:57:00Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: java-service-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: java-service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: java-service-1.0.0
  name: java-service-dev
  namespace: polyglot-dev
  resourceVersion: "83941"
  uid: 81eba543-168d-4172-867c-270c01f59c74
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-service-dev
      app.kubernetes.io/name: java-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-service
        app.kubernetes.io/instance: java-service-dev
        app.kubernetes.io/name: java-service
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: production
        envFrom:
        - configMapRef:
            name: java-service-dev
        - secretRef:
            name: java-service-dev
        image: dainmusty/java-service:dev-latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: java-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: java-service-dev
      serviceAccountName: java-service-dev
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-06-04T22:57:00Z"
    lastUpdateTime: "2026-06-04T22:57:00Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-06-04T23:43:15Z"
    lastUpdateTime: "2026-06-04T23:43:15Z"
    message: ReplicaSet "java-service-dev-7688579797" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
