apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: polyglot-ingress
  namespace: polyglot-dev

spec:
  ingressClassName: nginx  # Future AWS ALB Ingress Controller: alb

  rules:

  ##########################################################
  # JAVASCRIPT API
  ##########################################################

  - host: dashboard.local/api/js
    http:
      paths:
        - path: /api/js
          pathType: Prefix
          backend:
            service:
              name: javascript-api-dev
              port:
                number: 80

  ##########################################################
  # JAVA SERVICE
  ##########################################################

  - host: dashboard.local/api/java
    http:
      paths:
        - path: /api/java
          pathType: Prefix
          backend:
            service:
              name: java-service-dev
              port:
                number: 80

  ##########################################################
  # RUST PROCESSOR
  ##########################################################

  - host: dashboard.local/api/rust
    http:
      paths:
        - path: /api/rust
          pathType: Prefix
          backend:
            service:
              name: rust-processor-dev
              port:
                number: 80

  ##########################################################
  # REACT-DASHBOARD
  ##########################################################

  - host: react-dashboard.local
    http:
      paths:
        - path: /api/dashboard
          pathType: Prefix
          backend:
            service:
              name: react-dashboard-dev
              port:
                number: 80
